### ISSUE TITLE
Follow STAC best practices

### ISSUE THREAD

**Issue by fwfichtner** [dlr-eoc/ukis-pysat#155]
**Roadmap to move `ukis_pysat.data` to STAC**

- [x] Return metadata as pystac Items.
- [x] Develop our own STAC-API search class (inspired by [sat-search](https://github.com/sat-utils/sat-search/blob/master/satsearch/search.py)).
- [ ] Convert metadata items returned by data providers dynamically to [STAC Items according to best practises for different platforms](https://github.com/stac-utils/stac-sentinel). Currently we do this hardcoded and only for a small subset of attributes. The full set of attributes should also include the image band list.

_Originally posted by @MWieland in https://github.com/dlr-eoc/ukis-pysat/issues/23#issuecomment-862729500_

Could be based on these [packages](https://github.com/stactools-packages).

**Comment by fwfichtner** [comment]
In the next update we will only use stactools for creation. [Here](https://medium.com/radiant-earth-insights/a-belated-introduction-to-stactools-712f20e43fbc)'s a good summary of how that is helpful.

**Comment by fwfichtner** [comment]
That was maybe a bit rushed, we cannot use `stactools` because that would require downloading (and unzipping) the files first. We have only the response of the hubs and should instead **align** our items with the ones created with `stactools`.

**Comment by fwfichtner** [comment]
I guess a test which compares the resulting item with one created by stactools, e.g. directly using the [example](https://github.com/stactools-packages/sentinel1-grd/blob/main/examples/item.json) or [tests](https://github.com/stactools-packages/sentinel2/blob/main/tests/test_metadata.py).
