### ISSUE TITLE
Satellite image band list

### ISSUE THREAD

**Issue by MWieland** [dlr-eoc/ukis-pysat#23]
For any image preprocessing and analysis steps we should be able to store and keep track of the band information of a satellite image. In particular, we should know which band index refers to which wavelength and which unit (e.g. digital numbers, top of atmosphere, sigma naught, etc.). This is essential to be able to compute even the simplest band indices (e.g. NDVI) or to select an appropriate band subset during preprocessing. 

We have already a dedicated metadata attribute for this ("bandlist") but do not fill it upon metadata creation, because this information is not directly provided by the source metadata (e.g. EarthExplorer). It could like the following for a band subset of a Sentinel-2 image:

`'bandlist': [{'index':0, 'name':'B02', 'wavelength':'blue', 'unit':'DN'},
                  {'index':1, 'name':'B03', 'wavelength':'green', 'unit':'DN'},
                  {'index':2, 'name':'B04', 'wavelength':'red', 'unit':'DN'},
                  {'index':3, 'name':'B08', 'wavelength':'nir', 'unit':'DN'},
                  {'index':4, 'name':'B11', 'wavelength':'swir1', 'unit':'DN'},
                  {'index':5, 'name':'B12', 'wavelength':'swir2', 'unit':'DN'}]`

We could compile this ourselves from a bunch of lookup tables for unique combinations of "Platform" and "Producttype". We basically do this already [here ](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/raster.py#L236) for Landsat.

This should be put in a public place (possibly [here](https://github.com/dlr-eoc/ukis-pysat/blob/master/ukis_pysat/members.py)) and be expanded upon. Then we can compile the respective bandlist "on the fly" when we query the satellite image metadata. This would also allow a user to simply update it in a standardized way later on as part of a more complex processing chain.

**Comment by fwfichtner** [comment]
You could solve this with [enums](https://docs.python.org/3/library/enum.html) again.

**Comment by MWieland** [comment]
Good idea. Will give it a try. Thanks!

**Comment by fwfichtner** [comment]
Do we address this for 0.5.0 or shall we release?

**Comment by MWieland** [comment]
Would be great to put this into this release. Will try to find time this week to work on it. Deadline Friday 3 July alright?

**Comment by MWieland** [comment]
Let's move it to the next release. I simply can't find enough time these days to dedicate to develop it.

**Comment by fwfichtner** [comment]
@MWieland what is the status on this?

**Comment by MWieland** [comment]
This is not resolved yet. Moving an updated roadmap from #98 to here for completeness:

**Roadmap to move `ukis_pysat.data` to STAC**

- [x] Return metadata as pystac Items.
- [x] Develop our own STAC-API search class (inspired by [sat-search](https://github.com/sat-utils/sat-search/blob/master/satsearch/search.py)).
- [ ] Convert metadata items returned by data providers dynamically to [STAC Items according to best practises for different platforms](https://github.com/stac-utils/stac-sentinel). Currently we do this hardcoded and only for a small subset of attributes. The full set of attributes should also include the image band list.

**Comment by fwfichtner** [comment]
@shiwakotisurendra can you take care of that?

**Comment by fwfichtner** [comment]
@MWieland does #144 fix this?

**Comment by fwfichtner** [comment]
We will try to follow best practices more in the future -> #155
