### ISSUE TITLE
Make metadata a STAC

### ISSUE THREAD

**Issue by fwfichtner** [dlr-eoc/ukis-pysat#98]
Make our metadata a [SpatioTemporal Asset Catalogs](https://stacspec.org/) to be interoperable with other tools. We should also be able to extent it if we need more. @MWieland what do you think about this?

[pystac](https://github.com/stac-utils/pystac) might help with that.

And when we're on it we could make the creation of Cloud Optimized GeoTIFFs a default.

**Comment by fwfichtner** [comment]
We will break a lot of backwards compatibility for `ukis_psyat.data`.

**Comment by MWieland** [comment]
That is true, but it will make ukis-pysat future proof concerning all aspects related to metadata. In my opinion the benefits overweight the problems related to backwards compatibility by far. Compatibility, moreover, will potentially be affected almost exclusively by the way the metadata are returned (in particular the keys). Method calls should (almost) not be affected as far as I can see for now, since STAC follows a very similar approach to our current custom implementation. Even the returned metadata will be in the same file format (JSON) contain the same subset of attributes that we anyway follow already. Accessing metadata will change to some degree, but we gain the benefit of more flexibility, standardization and interoperability plus the options related to distributed catalogue queries etc.

**Comment by fwfichtner** [comment]
We should also dicsuss how we want to handly datetime, [here](https://github.com/radiantearth/stac-spec/blob/v1.0.0-beta.2/best-practices.md#datetime-selection)'s the best practice.

**Comment by MWieland** [comment]
**Roadmap to move `ukis_pysat.data` to STAC**

- [x] Return metadata as pystac Items
- [ ] Develop our own STAC-API search class (inspired by [sat-search](https://github.com/sat-utils/sat-search/blob/master/satsearch/search.py))
- [ ] Observe developments for [Landsat Collection 2 STAC access](https://landsatlook.usgs.gov/stac-browser) and change to new STAC-API as soon as it becomes operational -> this would effectively remove dependencies for pylandsat and landsatxplore
- [ ] ESA Scihub is not likely to support STAC in the near future, but we should ensure that items returned by queries with sentinelsat are converted on the fly to [STAC Items according to best practises](https://github.com/stac-utils/stac-sentinel). Currently we do this hardcoded and only for a small subset of attributes. Perhaps even [sentinelsat](https://github.com/sentinelsat/sentinelsat/issues/360) may support this feature in the next release.

**Comment by MWieland** [comment]
Reopening since discussion around this topic are still ongoing.

**Comment by MWieland** [comment]
Major point that we are currently still missing is the conversion of metadata to STAC best practises for specific sensors.

**Comment by fwfichtner** [comment]
As soon as we are happy we should consider adding this to [stacindex](https://stacindex.org/ecosystem?language=Python&category=Client) @MWieland.

**Comment by fwfichtner** [comment]
Let's create new issues, specific for each topic.
